# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.code.style=official
kotlin.incremental=false

# R8 Full Mode (کاهش حجم بیشتر)
android.enableR8.fullMode=true

# Resource optimization
android.nonTransitiveRClass=true
android.enableResourceOptimizations=true

# Disable unused features
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
android.defaults.buildfeatures.buildconfig=false

# Additional optimizations
android.bundle.enableUncompressedNativeLibs=false
android.injected.build.abi=arm64-v8a

